// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelChatStream(arg1) {
  return window['go']['app']['App']['CancelChatStream'](arg1);
}

export function ClearAIProviderAdminKey(arg1) {
  return window['go']['app']['App']['ClearAIProviderAdminKey'](arg1);
}

export function ClearAIProviderKey(arg1) {
  return window['go']['app']['App']['ClearAIProviderKey'](arg1);
}

export function CreateSession(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateSession'](arg1, arg2, arg3, arg4);
}

export function DeleteSession(arg1) {
  return window['go']['app']['App']['DeleteSession'](arg1);
}

export function GetAIProviderUsage(arg1) {
  return window['go']['app']['App']['GetAIProviderUsage'](arg1);
}

export function GetActiveProject() {
  return window['go']['app']['App']['GetActiveProject']();
}

export function GetPanelsState() {
  return window['go']['app']['App']['GetPanelsState']();
}

export function GetProjectTree() {
  return window['go']['app']['App']['GetProjectTree']();
}

export function GetSessionMessages(arg1) {
  return window['go']['app']['App']['GetSessionMessages'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function InitialWindowState() {
  return window['go']['app']['App']['InitialWindowState']();
}

export function ListAIProviderStatuses() {
  return window['go']['app']['App']['ListAIProviderStatuses']();
}

export function ListProjectFiles() {
  return window['go']['app']['App']['ListProjectFiles']();
}

export function ListSessions() {
  return window['go']['app']['App']['ListSessions']();
}

export function OpenDirectoryInExplorer(arg1) {
  return window['go']['app']['App']['OpenDirectoryInExplorer'](arg1);
}

export function OpenURLInDefaultBrowser(arg1) {
  return window['go']['app']['App']['OpenURLInDefaultBrowser'](arg1);
}

export function ReadProjectFile(arg1) {
  return window['go']['app']['App']['ReadProjectFile'](arg1);
}

export function SaveAIProviderAdminKey(arg1, arg2) {
  return window['go']['app']['App']['SaveAIProviderAdminKey'](arg1, arg2);
}

export function SaveChatMessage(arg1) {
  return window['go']['app']['App']['SaveChatMessage'](arg1);
}

export function SavePanelsState(arg1, arg2) {
  return window['go']['app']['App']['SavePanelsState'](arg1, arg2);
}

export function SaveWindowSize(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveWindowSize'](arg1, arg2, arg3);
}

export function SelectProjectFolder() {
  return window['go']['app']['App']['SelectProjectFolder']();
}

export function SendAIProviderTestMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendAIProviderTestMessage'](arg1, arg2, arg3);
}

export function SetActiveProject(arg1) {
  return window['go']['app']['App']['SetActiveProject'](arg1);
}

export function StartChatStream(arg1) {
  return window['go']['app']['App']['StartChatStream'](arg1);
}

export function UpdateMessageFeedback(arg1, arg2) {
  return window['go']['app']['App']['UpdateMessageFeedback'](arg1, arg2);
}

export function UpdateSessionTitle(arg1, arg2) {
  return window['go']['app']['App']['UpdateSessionTitle'](arg1, arg2);
}

export function ValidateAndSaveAIProviderKey(arg1, arg2) {
  return window['go']['app']['App']['ValidateAndSaveAIProviderKey'](arg1, arg2);
}

export function WriteProjectFile(arg1, arg2) {
  return window['go']['app']['App']['WriteProjectFile'](arg1, arg2);
}
