// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CancelChatStream(arg1:string):Promise<boolean>;

export function ClearAIProviderAdminKey(arg1:string):Promise<void>;

export function ClearAIProviderKey(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string,arg3:string,arg4:string):Promise<domain.Session>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetAIProviderUsage(arg1:string):Promise<domain.ProviderUsageResult>;

export function GetActiveProject():Promise<domain.ProjectInfo>;

export function GetPanelsState():Promise<domain.PanelsState>;

export function GetProjectTree():Promise<Array<domain.FileNode>>;

export function GetSessionMessages(arg1:string):Promise<Array<domain.ChatMessageRecord>>;

export function Greet(arg1:string):Promise<string>;

export function InitialWindowState():Promise<domain.WindowState>;

export function ListAIProviderStatuses():Promise<Array<domain.ProviderStatus>>;

export function ListProjectFiles():Promise<Array<domain.FileItem>>;

export function ListSessions():Promise<Array<domain.Session>>;

export function OpenDirectoryInExplorer(arg1:string):Promise<void>;

export function OpenURLInDefaultBrowser(arg1:string):Promise<void>;

export function ReadProjectFile(arg1:string):Promise<string>;

export function SaveAIProviderAdminKey(arg1:string,arg2:string):Promise<void>;

export function SaveChatMessage(arg1:domain.ChatMessageRecord):Promise<void>;

export function SavePanelsState(arg1:boolean,arg2:boolean):Promise<void>;

export function SaveWindowSize(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SelectProjectFolder():Promise<domain.ProjectInfo>;

export function SendAIProviderTestMessage(arg1:string,arg2:string,arg3:string):Promise<domain.TestMessageResult>;

export function SetActiveProject(arg1:string):Promise<domain.ProjectInfo>;

export function StartChatStream(arg1:domain.ChatStreamRequest):Promise<void>;

export function UpdateMessageFeedback(arg1:string,arg2:string):Promise<void>;

export function UpdateSessionTitle(arg1:string,arg2:string):Promise<void>;

export function ValidateAndSaveAIProviderKey(arg1:string,arg2:string):Promise<domain.ProviderValidationResult>;

export function WriteProjectFile(arg1:string,arg2:string):Promise<void>;
