// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveProject() {
  return window['go']['main']['App']['GetActiveProject']();
}

export function GetPanelsState() {
  return window['go']['main']['App']['GetPanelsState']();
}

export function GetProjectTree() {
  return window['go']['main']['App']['GetProjectTree']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListProjectFiles() {
  return window['go']['main']['App']['ListProjectFiles']();
}

export function OpenDirectoryInExplorer(arg1) {
  return window['go']['main']['App']['OpenDirectoryInExplorer'](arg1);
}

export function OpenURLInDefaultBrowser(arg1) {
  return window['go']['main']['App']['OpenURLInDefaultBrowser'](arg1);
}

export function ReadProjectFile(arg1) {
  return window['go']['main']['App']['ReadProjectFile'](arg1);
}

export function SavePanelsState(arg1, arg2) {
  return window['go']['main']['App']['SavePanelsState'](arg1, arg2);
}

export function SaveWindowSize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWindowSize'](arg1, arg2, arg3);
}

export function SelectProjectFolder() {
  return window['go']['main']['App']['SelectProjectFolder']();
}

export function SetActiveProject(arg1) {
  return window['go']['main']['App']['SetActiveProject'](arg1);
}

export function WriteProjectFile(arg1, arg2) {
  return window['go']['main']['App']['WriteProjectFile'](arg1, arg2);
}
