// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPanelsState():Promise<main.PanelsState>;

export function Greet(arg1:string):Promise<string>;

export function SavePanelsState(arg1:boolean,arg2:boolean):Promise<void>;

export function SaveWindowSize(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SaveWindowState(arg1:main.WindowState):Promise<void>;
