// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetActiveProject():Promise<domain.ProjectInfo>;

export function GetPanelsState():Promise<domain.PanelsState>;

export function GetProjectTree():Promise<Array<domain.FileNode>>;

export function Greet(arg1:string):Promise<string>;

export function ListProjectFiles():Promise<Array<domain.FileItem>>;

export function OpenDirectoryInExplorer(arg1:string):Promise<void>;

export function OpenURLInDefaultBrowser(arg1:string):Promise<void>;

export function ReadProjectFile(arg1:string):Promise<string>;

export function SavePanelsState(arg1:boolean,arg2:boolean):Promise<void>;

export function SaveWindowSize(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SelectProjectFolder():Promise<domain.ProjectInfo>;

export function SetActiveProject(arg1:string):Promise<domain.ProjectInfo>;

export function WriteProjectFile(arg1:string,arg2:string):Promise<void>;
