// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPanelsState() {
  return window['go']['main']['App']['GetPanelsState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SavePanelsState(arg1, arg2) {
  return window['go']['main']['App']['SavePanelsState'](arg1, arg2);
}

export function SaveWindowSize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWindowSize'](arg1, arg2, arg3);
}

export function SaveWindowState(arg1) {
  return window['go']['main']['App']['SaveWindowState'](arg1);
}
